name: $(Build.DefinitionName)-$(date:yyyyMMdd)$(rev:.r)
trigger:
  branches:
    include:
    - 'master'
    - 'develop/*'
    - 'release/*'
    - 'feature/*'
    - 'hotfix'
  paths:
    include:
    - 'Services'
pool:
  vmImage: 'Ubuntu-16.04'
resources:
- repo: self
  clean: true

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: CopyFiles@2
  displayName: 'Copy Release Scripts'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/Scripts'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Scripts'

- task: ArchiveFiles@2
  displayName: 'Zip Build Output'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Services/AzureFunctions/bin/Debug/netcoreapp2.1'
    archiveType: 'zip'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/package.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'